### ISSUE TITLE
Create script to automate etcd installation

### ISSUE THREAD

**Issue by SunSince90** [CloudNativeSDWAN/cnwan-operator#39]
Maybe we should add these steps as a script to `scripts/etcd_init.sh` or similar...? Anything that decreases friction and gets the user up and running quickly is great! :D

_Originally posted by @ljakab in https://github.com/CloudNativeSDWAN/cnwan-operator/pull/25#discussion_r595446714_

**Comment by SunSince90** [comment]
partly fixed by #42 . Can we close this @ljakab? I think that a script to install it is not really needed as the documentation is pretty easy to follow and all the one-liners are enough. What do you say

**Comment by ljakab** [comment]
I agree, the Kubernetes install is pretty straightforward, and we will soon even have the helm chart ready to automate everything (operator + etcd).
