### ISSUE TITLE
Create a Helm chart for the operator

### ISSUE THREAD

**Issue by ljakab** [CloudNativeSDWAN/cnwan-operator#44]
Installing the operator ideally should be as simple as `helm install cnwan-operator`. We should create a Helm chart that:
- Can install the operator with sensible defaults
- Allows customization of all the options currently available when installing manually
- Optionally pulls in and installs `etcd` using the `bitnami/etcd` chart, with sane defaults, but allowing customization of the most critical values

**Comment by SunSince90** [comment]
Closing this. For reference: https://github.com/CloudNativeSDWAN/cnwan-helm-charts
