### ISSUE TITLE
Remove default annotations

### ISSUE THREAD

**Issue by SunSince90** [CloudNativeSDWAN/cnwan-operator#9]
Currently, settings for the operator have `cnwan.io/profile` as default allowed annotations.

A new update will remove this, leaving the user complete choice during deployment phase.

**Comment by arnatal** [comment]
Just to clarify, is the default now just on the config that ships with the operator or is it hardcoded in the source?

**Comment by SunSince90** [comment]
That's correct, it's only on configmaps, no value is hard coded 🙂
